#!/usr/bin/env php
<?php

/*
 * This file is part of WordPlate.
 *
 * (c) Vincent Klaiber <hello@vinkla.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.'/bootstrap/autoload.php';

$app = new WordPlate\Console\Application(
    realpath(__DIR__)
);

$app->run();
