name: PSR-12

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    name: PSR-12

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
          tools: phpcs
      - run: phpcs --standard=PSR12 --colors -n public src
